# Homework I - ME 364 (Spring 2022)

**Question I :** Define a list with 5 elements, where at least one of the elements is a tuple itself. Then write a for-loop to print each element on a new line.

In [1]:
# Your code goes here
lst1 = [
        "a",
        "b",
        "c",
        "d",
        (5,"e")
]

for i in lst1:
    print(i)

a
b
c
d
(5, 'e')


**Question II :** Define a list with numbers from 1 to 6. Then add the numbers 7, 8, 9, 10, and 11 to the list

(a) using just one command

(b) using a loop and adding the numbers one by one

In [1]:
# Your code goes here

# Initialize list of numbers 1-6
lst2 = list(range(1,7))
print("List 2: {}".format(lst2))

# Add numbers 7-11 in a single line
lst2a = lst2 + list(range(7,12))
print("List 2a: {}".format(lst2a))

# Add numbers 7-11 using a loop
lst2b = lst2
for i in range(7,12):
    lst2b.append(i)

print("List 2b: {}".format(lst2b))


List 2: [1, 2, 3, 4, 5, 6]
List 2a: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11]
List 2b: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11]


**Quesion III :** Write a code that adds a new $key-value$ (of your choice) to
```python
SampleDictionary = {'ME 364' : '9am', 'Pyhon for Data Analysis' : '6:10pm', 'Reinforcement Learning' : '10am'}
```
Removes the $key-value$ ``` 'Reinforcement Learning' : '10am' ```, and then creates a _list_ of the $values$.


In [10]:
# Your code goes here
SampleDictionary = {'ME 364' : '9am', 'Pyhon for Data Analysis' : '6:10pm', 'Reinforcement Learning' : '10am'}
SampleDictionary['NewKey'] = 'NewVal'
SampleDictionary.pop('Reinforcement Learning')
SampleDictionaryValues = SampleDictionary.values()
print(SampleDictionaryValues)

dict_values(['9am', '6:10pm', 'NewVal'])


**Question IV :** Convert the following string
```python
Str = 'This string is written for homework I'
```
into a list and then slice it such that the outcome is
```python
['T', 'i', ' ', 't', 'i', 'g', 'i', ' ', 'r', 't', 'e', ' ', 'o', ' ', 'o', 'e', 'o', 'k', 'I']
```

In [11]:
# Your code goes here
Str = 'This string is written for homework I'
lst3 = list(Str)
lst3a = lst3[::2]
print(lst3a)

['T', 'i', ' ', 't', 'i', 'g', 'i', ' ', 'r', 't', 'e', ' ', 'o', ' ', 'o', 'e', 'o', 'k', 'I']


**Question V :** Write a function that adds the numbers from 1 to N, where N is the input to the function and the sum from 1 to N is the output.  Test it with N=100.

In [12]:
# Your code goes here
def sumOneThroughN(N):
    return sum(range(1,N+1))

print(sumOneThroughN(100))

5050


**Question VI :** The Chudnovsky series for approximating $\pi$ was used to obtain the world record for digits of $\pi$, 2.7 trillion digits! The
following series is a modified version of that series:

$$
12 \sum_{k=1}^N\frac{(-1)^k(6k)(1359+5451k)}{(3k)(k^3)(6^{3k+3/2})}
$$

Write a code that computs this series for N=10. 

<font color='blue'>Note:</font> The series no longer approximate $\frac{1}{\pi}$ since it has been modified.




In [19]:
# Your code goes here
print( 12*sum([ ((-1)**k * 6*k * (1359+5451*k)) / (3*k * k**3 * (6**(3*k+3/2))) for k in range(1,11) ]) )

-51.431108582998405


**Question VII:** Consider matrix
$A=\begin{bmatrix} 10 & 15 & 8 & 23 & 13\\ 19 & 22 & 45 & 3 & 34\\ 52 & 55 & 40 & 16 & 12\end{bmatrix}$

(a) Find a matrix that its elements are the squre roots of this matrix's elements.

(b) Calculate $(A^{T}A)^{-1}$

(c) Find the sum of all the elements across the columns and standard deviation for each column.

(d) Sort the elements down the rows.

(e) Make a slice that has the elements on rows 2 and 3 and columns 2 to 4

(f) Reshape the matrix into the following array:
$\begin{bmatrix} 10 & 15 & 8 & 23 & 13 & 19 & 22 & 45 & 3 & 34 & 52 & 55 & 40 & 16 & 12\end{bmatrix}$



In [50]:
# Your code goes here

# Import Numpy
import numpy as np

# Initialize matrix as defined above
A = np.array(
    [[10, 15, 8, 23, 13],
     [19, 22, 45, 3, 34],
     [52, 55, 40, 16, 12]]
)

# (b) Find matrix of square roots of each element in matrix A
B = np.sqrt(A)
print("(a):\n{}\n".format(B))

# (b) Calculate (A^T A)^-1
C = np.linalg.inv(np.matmul(A.T, A))
print("(b):\n{}\n".format(C))

# (c) Find the sum of all the elements across the columns of matrix A and standard deviation for each column.
print("(c):")
sumsAndDevs = []
for i, col in enumerate(A.T):
    print("Column {}: sum={}, std={}".format(i+1, sum(col), np.std(col)))
print()

# (d) Sort the elements down the rows.
D = [sorted(row) for row in A]
print("(d):\n{}\n".format(D))

# (e) Make a slice that has the elements on rows 2 and 3 and columns 2 to 4
E = A[1:, 1:4]
print("(e):\n{}\n".format(E))

# (f) Reshape the matrix into the following array: [10 15 8 23 13 19 22 45 3 34 52 55 40 16 12]
F = A.reshape(15)
print("(f):\n{}\n".format(F))

(a):
[[3.16227766 3.87298335 2.82842712 4.79583152 3.60555128]
 [4.35889894 4.69041576 6.70820393 1.73205081 5.83095189]
 [7.21110255 7.41619849 6.32455532 4.         3.46410162]]

(b):
[[-3.63554147e+12  5.46172830e+12 -2.48306347e+12 -2.23757826e+12
   1.98140753e+12]
 [ 7.33302725e+12 -8.28384971e+12  1.16884197e+12  2.07194931e+12
  -4.67545909e+11]
 [-5.11237264e+12  3.84080113e+12  1.90316852e+12  2.83718640e+11
  -2.17224365e+12]
 [-3.90937468e+12  3.43177975e+12  7.60156187e+11 -2.25057783e+11
  -1.02214385e+12]
 [ 4.39804651e+12 -3.07822160e+12 -1.95468734e+12 -4.45913626e+11
   2.16049008e+12]]

(c):
Column 1: sum=81, std=18.05547008526779
Column 2: sum=92, std=17.441967269268172
Column 3: sum=93, std=16.391054470858997
Column 4: sum=42, std=8.286535263104035
Column 5: sum=59, std=10.143416036468626

(d):
[[8, 10, 13, 15, 23], [3, 19, 22, 34, 45], [12, 16, 40, 52, 55]]

(e):
[[22 45  3]
 [55 40 16]]

(f):
[10 15  8 23 13 19 22 45  3 34 52 55 40 16 12]

